Lind.DDD.Manager/Controllers/AdminCommonController.cs
using Lind.DDD.Authorization;
using Lind.DDD.Domain;
using Lind.DDD.Manager.Models;
using Lind.DDD.Manager.ViewModels;
using Lind.DDD.TreeHelper;
using Lind.DDD.Utils;
using PureCat;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Text;
using System.Web.Mvc;
namespace Lind.DDD.Manager.Controllers
{
   
    /// <summary>
    /// 公用模块
    /// </summary>
    public class AdminCommonController : BaseController
    {
        private IEnumerable<WebManageMenus> menuList;

        private List<int> MenuIdArr = new List<int>();

        List<WebDepartments> DeptDB;
        public AdminCommonController()
        {
            if (CurrentUser.IsLogin)
                MenuIdArr = Lind.DDD.Utils.SerializeMemoryHelper.DeserializeFromJson<List<Tuple<int, string, int>>>(CurrentUser.ExtInfo).Select(i => i.Item1).ToList();
            menuList = menuRepository.GetModel(i => i.Level == 1 && MenuIdArr.Contains(i.Id)).ToList();

            DeptDB = departmentsRepository.GetModel().ToList();

        }
        public string Test()
        {
            return base.CommonAreaProvince();
        }
        public ActionResult ModifyPassword()
        {
            return View();
        }
        [HttpPost]
        public ActionResult ModifyPassword(ModifyPasswordModel model)
        {
            if (string.IsNullOrWhiteSpace(model.OldPassword)
            || string.IsNullOrWhiteSpace(model.NewPassword)
            || string.IsNullOrWhiteSpace(model.ConfirmPassword))
            {
                ModelState.AddModelError("", "请认真填写密码！");
                return View();
            }


            string oldPassword = Lind.DDD.Utils.Encryptor.Utility.EncryptString(model.OldPassword, Lind.DDD.Utils.Encryptor.Utility.EncryptorType.MD5);
            string newPassword = Lind.DDD.Utils.Encryptor.Utility.EncryptString(model.NewPassword, Lind.DDD.Utils.Encryptor.Utility.EncryptorType.MD5);

            var old = userRepository.Find(i => i.LoginName == CurrentUser.UserName && i.Password == oldPassword);
            if (old == null)
            {
                ModelState.AddModelError("", "原密码不正确！");
                return View();
            }

            if (model.NewPassword != model.ConfirmPassword)
            {
                ModelState.AddModelError("", "新密码和确认密码必须相同！");
                return View();
            }

            old.Password = newPassword;
            userRepository.Update(old);
            ViewBag.Msg = "<span style='color: green;font-size: 1.1em;font-weight:bold;'>密码成功修改，请重新<a href='/AdminCommon/Logon'>登陆</a></span>";
            return View();
        }


        #region 菜单相关
        public string TopMenu()
        {

            var menu = new DataTree<WebManageMenus>(menuRepository.GetModel(i => i.IsDisplayMenuTree && MenuIdArr.Contains(i.Id))
                                                                  .OrderBy(i => i.SortNumber)
                                                                  .ToList());

            return menu.CreateTreeUL(menuRepository.Find(i => i.Level == 0));
        }

        /// <summary>
        /// 找儿子菜单
        /// </summary>
        /// <param name="menuList"></param>
        private void FindMenuSonsTree(IEnumerable<WebManageMenus> menuList)
        {

            foreach (var item in menuList)
            {
                item.Sons = menuRepository.GetModel()
                    .Where(i => i.IsDisplayMenuTree && i.ParentID == item.Id && MenuIdArr.Contains(i.Id))
                    .ToList();
                if (item.Sons != null && item.Sons.Count() > 0)//如果子树，加加载这块
                {
                    this.FindMenuSonsTree(item.Sons);
                }

            }

        }
        #endregion

        #region 部门&角色相关
        /// <summary>
        /// 找儿子部门
        /// </summary>
        /// <param name="menuList"></param>
        private void FindDeptSonsTree(IEnumerable<WebDepartments> deptList, List<int> deptArr)
        {

            foreach (var item in deptList)
            {
                deptArr.Add(item.Id);
                item.Sons = DeptDB
                    .Where(i => i.ParentID == item.Id)
                    .ToList();
                if (item.Sons != null && item.Sons.Count() > 0)//如果子树，加加载这块
                {
                    this.FindDeptSonsTree(item.Sons, deptArr);
                }

            }

        }

        private void FindDeptFatherTree(WebDepartments dept, List<int> fatherList)
        {
            if (dept != null)
            {
                dept.Father = DeptDB.FirstOrDefault(i => i.Id == dept.ParentID);
                fatherList.Add(dept.ParentID ?? 0);
                FindDeptFatherTree(dept.Father, fatherList);
            }

        }
        /// <summary>
        /// 部门－下拉列表
        /// </summary>
        /// <param name="deptId"></param>
        /// <returns></returns>
        public PartialViewResult Dept_SelectList(int deptId = 0)
        {
            return Dept_Role_SelectList(deptId, 0);
        }
        /// <summary>
        /// 部门－角色－下拉列表
        /// </summary>
        /// <param name="dataSetTypeId"></param>
        /// <param name="id"></param>
        /// <returns></returns>
        public PartialViewResult Dept_Role_SelectList(int deptId = 0, int roleId = 0)
        {
            var deptList = new List<SelectListItem>();
            deptList = new List<SelectListItem>(departmentsRepository.GetModel().Select(i => new SelectListItem
           {
               Text = i.Name,
               Value = i.Id.ToString(),
               Selected = i.Id == deptId ? true : false
           }));
            deptList.Insert(0, new SelectListItem { Text = "请选择", Value = "0", Selected = true });

            var roleList = new List<SelectListItem>();

            if (deptId > 0)
            {
                roleList = new List<SelectListItem>(roleRepository.GetModel(i => i.DepartmentID == deptId).Select(i => new SelectListItem
                {
                    Text = i.RoleName,
                    Value = i.Id.ToString(),
                    Selected = i.Id == roleId ? true : false
                }));
            }
            roleList.Insert(0, new SelectListItem { Text = "请选择", Value = "0", Selected = true });
            ViewBag.roleList = roleList;
            ViewBag.deptList = deptList;

            StringBuilder str = new StringBuilder();
            List<int> fatherList = new List<int>();
            var father = new WebDepartments();
            if (deptId > 0)
            {
                father = departmentsRepository.GetModel().FirstOrDefault(i => i.Id == deptId);
                fatherList.Add(deptId);

            }
            else
            {
                father = departmentsRepository.GetModel().FirstOrDefault(i => i.Level == 1);
                father.Sons = null;//默认“请选择”状态它的子列表为空
            }
            FindDeptFatherTree(father, fatherList);
            GetSelectListAll(father, str, fatherList);
            ViewBag.DeptStr = str.ToString();
            return PartialView();
        }



        #endregion

        [AllowAnonymous, HttpPost, ValidateInput(false)]
        public ActionResult Error(string msgErr = "请求发生错误")
        {
            ViewBag.Msg = msgErr;
            return View();
        }

        #region 登录—登出
        [AllowAnonymous]
        public ActionResult LogOn()
        {
            return View();
        }
        [AllowAnonymous]
        [HttpPost]
        public ActionResult LogOn(FormCollection form)
        {
            string userName = form["UserName"];
            string password = Lind.DDD.Utils.Encryptor.Utility.EncryptString(form["Password"], Lind.DDD.Utils.Encryptor.Utility.EncryptorType.MD5);

            try
            {
                var entity = userRepository.GetModel()
                                           .Include(i => i.WebManageRoles)
                                           .Include(i => i.WebDepartments)
                                           .FirstOrDefault(i => i.DataStatus == Status.Normal && i.LoginName == userName && i.Password == password);
                if (entity != null)
                {


                    #region 应用角色和菜单
                    var roleArr = entity.WebManageRoles.Select(j => j.Id).ToList();
                    var authority = 0;
                    var menuList = new List<Tuple<int, string, long>>();
                    var result = new List<Tuple<int, string, long>>();
                    if (entity.WebManageRoles != null && entity.WebManageRoles.Any())
                    {
                        //当前用户所有角色对应的权限列表
                        var auditList = webManageRoles_WebManageMenus_Authority_RRepository.GetModel()
                            .Include(i => i.WebManageRoles)
                            .Include(i => i.WebManageMenus)
                            .Where(i => roleArr.Contains(i.RoleId))
                            .ToList();

                        auditList.ForEach(i =>
                        {
                            menuList.Add(new Tuple<int, string, long>(i.MenuId, i.WebManageMenus.LinkUrl, i.Authority));
                        });

                        var linq = from m in menuList
                                   group m by new { m.Item1, m.Item2 } into p
                                   select new { ID = p.Key, score = p.BinaryOr(m => m.Item3) };

                        result = linq.Select(i => new Tuple<int, string, long>(i.ID.Item1, i.ID.Item2, i.score)).ToList();
                    }
                    #endregion

                    #region 部门（组织结构）
                    var deptArr = new List<int>();
                    if (entity.WebDepartments != null && entity.WebDepartments.Count > 0)
                    {
                        FindDeptSonsTree(entity.WebDepartments, deptArr);
                    }
                    #endregion

                    CurrentUser.Serialize(

Lind.DDD.Manager/Views/LindAdmin/Shared/TableList.cshtml
@model IEnumerable<Lind.DDD.Domain.Entity>
<table>
    <tr>
        @{
            var t = Model.GetType().GenericTypeArguments[0].GetProperties().Where(i => i.PropertyType.IsValueType || i.PropertyType == typeof(string));
        }
        @foreach (var property in t)
        {
            string propertyName = property.Name;
            var tAttr = property.GetCustomAttributes(typeof(System.ComponentModel.DisplayNameAttribute), false);
            if (tAttr != null && tAttr.Count() > 0)
            {
                propertyName = (tAttr.FirstOrDefault() as System.ComponentModel.DisplayNameAttribute).DisplayName;
            }
            <th>@propertyName</th>
        }
        <th></th>
    </tr>

    @foreach (var item in Model)
    { 
        <tr>
            @foreach (var property in t)
            {
                <td>@property.GetValue(item)</td>
            }
            <td>@Html.ActionLink("详细", "Details", new { id = item.Id }, new { @class = "btn btn-primary btn-sm" })
                @Html.ActionLink("删除", "Delete", new { id = item.Id }, new { @class = "btn btn-warning btn-sm" })
                @Html.ActionLink("编辑", "Edit", new { id = item.Id }, new { @class = "btn btn-success btn-sm" })
            </td>
        </tr>
    }
</table>

Lind.DDD.Manager/Views/LindAdmin/Shared/_Layout.cshtml
@{
    Layout = "~/Views/LindAdmin/Shared/_LayoutInit.cshtml";
}
@RenderSection("Scripts", required: false)

<nav class="navbar navbar-default" role="navigation">
    <div class="navbar-header" style="margin: 5px;">
        @if (System.Configuration.ConfigurationManager.AppSettings["PageHeadLogo"] != null)
        {
            <img src="@(System.Configuration.ConfigurationManager.AppSettings["PageHeadLogo"])">
        }
        <span style="font-size: 30px; font-family: 微软雅黑;">@(System.Configuration.ConfigurationManager.AppSettings["PageHead"] ?? "后台管理系统")</span>
    </div>
    <ul class="nav navbar-nav navbar-right" style="margin: 5px;">
        <li>
            <a class="navbar-link">【当前用户：<span style="color: red;">@(Lind.DDD.Authorization.CurrentUser.UserName)</span>】</a>
        </li>
        <li><a href="/" class="navbar-link">后台首页</a></li>
        <li><a href="@Url.Action("ModifyPassword", "AdminCommon")" class="navbar-link">修改密码</a></li>
        <li><a href="@Url.Action("LogOut", "AdminCommon")" class="navbar-link">登出</a></li>
    </ul>
</nav>
<ol class="breadcrumb">
    @Html.BreadCrumb()
</ol>
<div class="row">
    <div class="col-md-2">
        <div class="panel panel-default">
            <div class="panel-heading">
                菜单导航
            </div>
            <div class="panel-body">
                @Html.Action("TopMenu", "AdminCommon")
            </div>
        </div>
    </div>
    <div class="col-md-10">
        <div class="panel panel-default">
            <div class="panel-heading">
                @ViewBag.Title
            </div>
            <div class="panel-body">
                @RenderBody()
            </div>
        </div>
    </div>
</div>

<nav class="navbar navbar-default" style="min-height: 20px;">
    <div class="container">
        <ins>@(System.Configuration.ConfigurationManager.AppSettings["PageFoot"] ?? "仓储大叔对技术的追求永不止步！")</ins>
    </div>
</nav>

<!-- system modal start -->
<div id="ycf-alert" class="modal">
    <div class="modal-dialog modal-sm">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                <h5 class="modal-title"><i class="fa fa-exclamation-circle"></i>[Title]</h5>
            </div>
            <div class="modal-body small">
                <p>[Message]</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary ok" data-dismiss="modal">[BtnOk]</button>
                <button type="button" class="btn btn-default cancel" data-dismiss="modal">[BtnCancel]</button>
            </div>
        </div>
    </div>
</div>
<!-- system modal end -->
<div id="ycf-box" class="modal">
    <div class="modal-dialog modal-sm">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                <h5 class="modal-title"><i class="fa fa-exclamation-circle"></i>[Title]</h5>
            </div>
            <div class="modal-body small">
                <p>[Message]</p>
            </div>
        </div>
    </div>
</div>

<script type="text/ecmascript">

    //bootstrape的样式加载
    function bootstrapeCss() {
        //按钮
        $("input[type=submit]").addClass("btn btn-primary");
        $("button").addClass("btn btn-primary");
        $("label").addClass("control-label");
        $("table").addClass("table table-hover table-bordered table-striped");
        $("input[type=text],input[type=password]").addClass("form-control");
    }

    //复写模式窗口
    $(function () {

        //级联菜单支持IOS系统
        $(".dropdown a").click(function (e) {
        });

        //高亮导航
        var o = $(".nav").find("li").find("a[href$='@Request.Url.AbsolutePath']");
        o.closest("li").addClass("active").siblings().removeClass("active");
        o.parents(".dropdown").addClass("active").siblings().removeClass("active");
        bootstrapeCss();
    });
    //复写模式窗口
    $(function () {
        window.Modal = function () {
            var reg = new RegExp("\\[([^\\[\\]]*?)\\]", 'igm');
            var alr = $("#ycf-alert");
            var ahtml = alr.html();
            var box = $("#ycf-box");
            var boxhtml = box.html();

            var _alert = function (options) {
                alr.html(ahtml);    // 复原
                alr.find('.ok').removeClass('btn-success').addClass('btn-primary');
                alr.find('.cancel').hide();
                _dialog(options);

                return {
                    on: function (callback) {
                        if (callback && callback instanceof Function) {
                            alr.find('.ok').click(function () { callback(true) });
                        }
                    }
                };
            };

            var _confirm = function (options) {
                alr.html(ahtml); // 复原
                alr.find('.ok').removeClass('btn-primary').addClass('btn-success');
                alr.find('.cancel').show();
                _dialog(options);

                return {
                    on: function (callback) {
                        if (callback && callback instanceof Function) {
                            alr.find('.ok').click(function () { callback(true) });
                            alr.find('.cancel').click(function () { callback(false) });
                        }
                    }
                };
            };
            var _box = function (options) {
                var ops = {
                    msg: "提示内容",
                    title: "操作提示"
                };
                $.extend(ops, options);

                var html = boxhtml.replace(reg, function (node, key) {
                    return {
                        Title: ops.title,
                        Message: ops.msg
                    }[key];
                });
                box.modal({
                    width: 500,
                    backdrop: 'static'
                });
            };

            var _dialog = function (options) {
                var ops = {
                    msg: "提示内容",
                    title: "操作提示",
                    btnok: "确定",
                    btncl: "取消"
                };

                $.extend(ops, options);

                var html = alr.html().replace(reg, function (node, key) {
                    return {
                        Title: ops.title,
                        Message: ops.msg,
                        BtnOk: ops.btnok,
                        BtnCancel: ops.btncl
                    }[key];
                });

                alr.html(html);
                alr.modal({
                    width: 500,
                    backdrop: 'static'
                });
            }

            return {
                alert: _alert,
                confirm: _confirm,
                box: _box
            }

        }();
    });

    // 四个选项都是可选参数
    //Modal.alert(
    //    {
    //        msg: '内容',
    //        title: '标题',
    //        btnok: '确定',
    //        btncl: '取消'
    //    });

    // 如需增加回调函数，后面直接加 .on( function(e){} );
    // 点击“确定” e: true
    // 点击“取消” e: false
    //Modal.confirm(
    //    {
    //        msg: "是否删除角色？"
    //    })
    //    .on(function (e) {
    //        alert("返回结果：" + e);
    //    });
</script>

Lind.DDD.Manager/Views/LindAdmin/Shared/_LayoutInit.cshtml
<!DOCTYPE html>
<html lang="zh">
<head>
    <meta http-equiv="X-UA-Compatible" content="IE=8">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <title>@ViewBag.Title</title>
    <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
    <meta name="viewport" content="width=device-width" />
    @Styles.Render("~/bundles/bootstraps/css")
    <link href="~/Content/bootstraps/CSS/bootstrap-submenu.css" rel="stylesheet" />
    <link href="~/Scripts/JQTree/themes/default/style.css" rel="stylesheet" />
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstraps/js")
    @RenderSection("Scripts", required: false)
    <script src="~/Scripts/knockout-2.1.0.js"></script>
    <!-- 多级菜单JS-->
    <script src="~/Content/bootstraps/JS/docs.js"></script>
    <script src="~/Content/bootstraps/JS/bootstrap-submenu.js"></script>
    <!-- 结果多级菜单JS-->
    <script src="~/Scripts/JQTree/jquery.jstree.js"></script>
    <script src="~/Content/bootstraps/JS/Respond.js"></script>
    <script src="~/Scripts/JS/ajaxLoading.js"></script>

    <script>function detailDialog(id) {
    $.ajaxLoading({
        url: '/@(Request.RequestContext.RouteData.Values["controller"])/Details?id=' + id,
        type: "get",
        success: function (data) {
            $('#dialogContent').html(data);
        }
    });
}
    </script>
    <style type="text/css">
        .validation-summary-errors ul {
            margin: 0px;
            padding-left: 10px;
        }

            .validation-summary-errors ul li {
                color: red;
                list-style-type: square;
            }
    </style>
</head>
<body>
    <!-- 弹层 -->
    <div class="modal fade" id="myModal" tabindex="-1" role="dialog"
        aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close"
                        data-dismiss="modal" aria-hidden="true">
                        &times;
                    </button>
                    <h4 class="modal-title" id="myModalLabel">详细
                    </h4>
                </div>
                <div class="modal-body" id="dialogContent">
                </div>
                @*<div class="modal-footer">
                    <button type="button" class="btn btn-default"
                        data-dismiss="modal">
                        关闭
                    </button>
                    <button type="button" class="btn btn-primary">
                        提交更改
                    </button>
                </div>*@
            </div>
            <!-- /.modal-content -->
        </div>
    </div>

    <div class="container-fluid">
        @RenderBody()
    </div>
</body>
</html>